# Generated by Django 4.1.6 on 2023-02-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="nick",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
