# Generated by Django 4.1.4 on 2023-01-15 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("guilds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guild",
            name="owner_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_guilds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="GuildMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nick",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guilds.guild",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "guilds_members",
            },
        ),
        migrations.AddField(
            model_name="guild",
            name="members",
            field=models.ManyToManyField(
                related_name="guilds",
                through="guilds.GuildMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
