# Generated by Django 4.1.4 on 2023-01-17 02:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guilds", "0002_alter_guild_owner_id_guildmember_guild_members"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guildmember",
            name="guild",
        ),
        migrations.RemoveField(
            model_name="guildmember",
            name="user",
        ),
    ]
