# Generated by Django 4.1.4 on 2023-01-17 02:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guilds", "0003_remove_guildmember_guild_remove_guildmember_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guild",
            name="members",
            field=models.ManyToManyField(
                related_name="guilds",
                through="members.Member",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="GuildMember",
        ),
    ]
