# Generated by Django 4.1.6 on 2023-02-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guilds", "0004_alter_guild_members_delete_guildmember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guild",
            name="description",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
