# Default compose file for development and production.
# Should be used directly in development.
# Automatically loads `docker-compose.override.yml` if it exists.
# No extra steps required.
# Should be used together with `docker/docker-compose.prod.yml`
# in production.

version: '3.9'

services:
  database:
    image: 'postgres:15.1-alpine'
    restart: unless-stopped
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - webnet
    env_file: ./config/.env
  web:
    <<: &web
      # Image name is changed in production:
      image: 'siege-api:dev'
      build:
        target: development_build
        context: .
        dockerfile: ./docker/django/Dockerfile
        args:
          DJANGO_ENV: development
        cache_from:
          - "siege-api:dev"
          - "siege-api:latest"
          - "*"
      depends_on:
        - database
      networks:
        - webnet
      env_file:
        - ./config/.env
      environment:
        DJANGO_DATABASE_HOST: database

    command: python -Wd manage.py runserver 0.0.0.0:8000

networks:
  # Network for your internals, use it by default:
  webnet:

volumes:
  postgresql:
