# Generated by Django 4.1.6 on 2023-02-25 04:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
        migrations.AlterModelTable(
            name="message",
            table="messages",
        ),
    ]
